# Generated by Django 3.2.3 on 2021-07-10 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhishingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Select_Template_Category', models.CharField(max_length=100, null=True)),
                ('select_country', models.CharField(max_length=100, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('sname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='')),
                ('count', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=100)),
                ('ttype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('eMail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Street', models.CharField(blank=True, max_length=50, null=True)),
                ('ciTy', models.CharField(blank=True, max_length=100, null=True)),
                ('sTate', models.CharField(blank=True, max_length=50, null=True)),
                ('zIp', models.CharField(blank=True, max_length=30, null=True)),
                ('site', models.CharField(blank=True, max_length=30, null=True)),
                ('FaceBook', models.CharField(blank=True, max_length=30, null=True)),
                ('Organization_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Job_Title', models.CharField(blank=True, max_length=30, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
