# Generated by Django 3.2.3 on 2021-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('eMail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('ciTy', models.CharField(max_length=100)),
                ('sTate', models.CharField(max_length=50)),
                ('zIp', models.CharField(max_length=30)),
                ('Street', models.CharField(max_length=30)),
                ('FaceBook', models.CharField(max_length=30)),
                ('Organization_Name', models.CharField(max_length=30)),
                ('Job_Title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
