# Generated by Django 3.2.3 on 2021-06-03 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
