# Generated by Django 3.2.3 on 2021-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.CharField(default='some string', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Street',
            field=models.CharField(max_length=50),
        ),
    ]
