# Generated by Django 3.2.3 on 2021-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('sname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('myfile', models.FileField(upload_to='')),
                ('count', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=100)),
                ('ttype', models.CharField(max_length=100)),
            ],
        ),
    ]
