# Generated by Django 3.2.3 on 2021-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
