# Generated by Django 3.2.3 on 2021-06-21 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210621_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template_Category',
        ),
        migrations.AddField(
            model_name='form',
            name='Select_Template_Category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
