# Generated by Django 3.2.3 on 2021-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_form_select_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='select_country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
