# Generated by Django 3.2.3 on 2021-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_form_select_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
