# Generated by Django 3.2.3 on 2021-06-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timestamp',
            new_name='added_on',
        ),
    ]
