# Generated by Django 3.2.3 on 2021-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_form_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
