# Generated by Django 3.2.3 on 2021-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_alter_form_select_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Select_Template_Category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
