# Generated by Django 3.2.3 on 2021-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
