# Generated by Django 3.2.3 on 2021-06-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Phising',
        ),
    ]
