# Generated by Django 3.2.3 on 2021-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_rename_phising_phishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
