# Generated by Django 3.2.3 on 2021-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_phishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishing',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
