# Generated by Django 3.2.3 on 2021-07-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_alter_phishing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishing',
            name='date',
        ),
    ]
