# Generated by Django 3.2.3 on 2021-07-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_remove_phishing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishing',
            name='user',
        ),
    ]
